AWSTemplateFormatVersion: 2010-09-09
Parameters:
    Image:
        Type: String
        Description: The image to deploy
Resources:
    P4Ec2SecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupName: P4Ec2SecurityGroup
            GroupDescription: Enable SSH and HTTP traffic
            SecurityGroupIngress:
                -   CidrIp: 0.0.0.0/0
                    IpProtocol: '-1'
                    FromPort: -1
                    ToPort: -1
    P4Ec2Cluster:
        Type: AWS::ECS::Cluster
        Properties:
            ClusterName: P4Ec2Cluster
    P4Ec2Instance:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: ami-0230bd60aa48260c6
            InstanceType: t2.micro
            KeyName: Web_server
            SecurityGroupIds:
                - !GetAtt P4Ec2SecurityGroup.GroupId
            UserData:
                Fn::Base64: |
                    #!/bin/bash
                    echo "ECS_CLUSTER=P4Ec2Cluster" >> /etc/ecs/ecs.config
            Tags:
                -   Key: Name
                    Value: P4Ec2Instance
    P4Ec2Task:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: P4Ec2Task
            ContainerDefinitions:
                -   Name: P4Container
                    Image: !Ref Image
                    PortMappings:
                        -   ContainerPort: 80
                            HostPort: 80
                            Protocol: http
            Cpu: 1024
            Memory: 3072
            TaskRoleArn: arn:aws:iam::989870301024:role/LabRole
            ExecutionRoleArn: arn:aws:iam::989870301024:role/LabRole
            RequiresCompatibilities:
                - EC2
    P4Ec2Service:
        Type: AWS::ECS::Service
        Properties:
            Cluster: !Ref P4Ec2Cluster
            DesiredCount: 1
            LaunchType: EC2
            TaskDefinition: !Ref P4Ec2Task
