AWSTemplateFormatVersion: 2010-09-09
Resources:
    #    P4Repository:
    #        Type: AWS::ECR::Repository
    #        Properties:
    #            EmptyOnDelete: true
    #            RepositoryName: p4
    P4Cluster:
        Type: AWS::ECS::Cluster
        Properties:
            ClusterName: P4FargateCluster
    P4ServerTask:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: P4FargateTask
            ContainerDefinitions:
                -   Name: P4Container
                    Image: {{image}}
                    PortMappings:
                        -   ContainerPort: 80
                            HostPort: 80
                            Protocol: http
            Cpu: 1024
            Memory: 3072
            TaskRoleArn: arn:aws:iam::989870301024:role/LabRole
            ExecutionRoleArn: arn:aws:iam::989870301024:role/LabRole
            NetworkMode: awsvpc
            RequiresCompatibilities:
                - FARGATE
    P4Service:
        Type: AWS::ECS::Service
        Properties:
            Cluster: !Ref P4Cluster
            DesiredCount: 1
            LaunchType: FARGATE
            NetworkConfiguration:
                AwsvpcConfiguration:
                    AssignPublicIp: ENABLED
                    Subnets:
                        - subnet-00f75e8296c3061d1
                    SecurityGroups:
                        - sg-09e18967b01cc2416
            TaskDefinition: !Ref P4ServerTask
