AWSTemplateFormatVersion: 2010-09-09
Resources:
    MyECSTaskExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: MyECSTaskExecutionRole
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    -   Effect: Allow
                        Principal:
                            Service:
                                - ecs-tasks.amazonaws.com
                        Action:
                            - sts:AssumeRole
            Policies:
                -   PolicyName: ECSTaskExecutionPolicy
                    Resource: "*"
                    PolicyDocument:
                        Version: 2012-10-17
                        Statement:
                            -   Effect: Allow
                                Action:
                                    - "ecs:*"
    P4Repository:
        Type: AWS::ECR::Repository
        Properties:
            EmptyOnDelete: true
            RepositoryName: p4
    P4Cluster:
        Type: AWS::ECS::Cluster
        Properties:
            ClusterName: P4Cluster
    P4ServerTask:
        Type: AWS::ECS::TaskDefinition
        Properties:
            ContainerDefinitions:
                -   Name: P4Container
                    Image: !GetAtt P4Repository.RepositoryUri
                    PortMappings:
                        -   ContainerPort: 80
                            HostPort: 80
                            AppProtocol: http
            Cpu: 512
            Memory: 1024
            TaskRoleArn: !GetAtt MyECSTaskExecutionRole.Arn
            NetworkMode: awsvpc
            RequiresCompatibilities:
                - FARGATE
    P4Service:
        Type: AWS::ECS::Service
        Properties:
            Cluster: !Ref P4Cluster
            DesiredCount: 1
            LaunchType: FARGATE
            NetworkConfiguration:
                AwsvpcConfiguration:
                    AssignPublicIp: ENABLED
            TaskDefinition: !Ref P4ServerTask
